### ISSUE TITLE
MongoDB Schema

### ISSUE THREAD

**Issue by goldylucks** [Backfeed/ChessMates#1]
Add a schema to mongoDB
relevant meteor package:
https://github.com/aldeed/meteor-collection2

Things to considerL
updatedAt
createdAt
validations
callbacks?

**Comment by goldylucks** [comment]
@jankei 
our first issue :+1:

**Comment by jankei** [comment]
very nice @Adam-Goldman7

**Comment by goldylucks** [comment]
This crashes the app around the third turn

Maybe there's a memory leak somewhere that makes everything exponentially slower with each move.

I'm leaving the branch "schema" for archiving purposes.
