### ISSUE TITLE
play sound at turn change

### ISSUE THREAD

**Issue by goldylucks** [Backfeed/ChessMates#41]

**Comment by ghost** [comment]
@Adam-Goldman7 FYI I said "sound" yesterday as a shortcut, but what I really meant was a notification. I suspect that beeping might be easier than activating desktop notification from the browser :)

**Comment by goldylucks** [comment]
You mean like this?
http://ttsvetko.github.io/HTML5-Desktop-Notifications/

Looks like it will be easy to implement :)
